export enum Cart {
    ADD_PIZZA_CART = 'ADD_PIZZA_CART',
    REMOVE_CART_ITEM = 'REMOVE_CART_ITEM',
    PLUS_CART_ITEM = 'PLUS_CART_ITEM',
    MINUS_CART_ITEM = 'MINUS_CART_ITEM',
    CLEAR_CART = 'CLEAR_CART'
}